### PR TITLE
Fix deisa bridge release not called

### LINKED ISSUE #534: deisa plugin bridge release() is never called

### PR DESCRIPTION
**Pull request by benoitmartin88**
This PR fixes a bug in deisa where the bridge's `release` method was never called.
Fixes #534 

# List of things to check before making a PR

Before merging your code, please check the following:

* [x] you have added a line describing your changes to the Changelog;
* [ ] you have added unit tests for any new or improved feature;
* [x] In case you updated dependencies, you have checked pdi/docs/CheckList.md
* you have checked your code format:
  - [x] you have checked that you respect all conventions specified in CONTRIBUTING.md;
  - [x] you have checked that the indentation and formatting conforms to the `.clang-format`;
  - [x] you have documented with doxygen any new or changed function / class;
* you have correctly updated the copyright headers:
  - [x] your institution is in the copyright header of every file you (substantially) modified;
  - [x] you have checked that the end-year of the copyright there is the current one;
* you have updated the AUTHORS file:
  - [x] you have added yourself to the AUTHORS file;
  - [x] if this is a new contribution, you have added it to the AUTHORS file;
* you have added everything to the user documentation:
  - [x] any new CMake configuration option;
  - [x] any change in the yaml config;
  - [x] any change to the public or plugin API;
  - [x] any other new or changed user-facing feature;
  - [x] any change to the dependencies;
* you have correctly linked your MR to one or more issues:
  - [x] your MR solves an identified issue;
  - [x] your commit contain the `Fix #issue` keyword to autoclose the issue when merged.

### CODE REVIEW

**Review by JAuriac — DISMISSED** [review]

**Comment by jbigot** [comment]
Please rebase it on top of and propose a merge into v1.8 so that we can publish a bugfix release

**Comment by jbigot** [comment]
looks like there is a lot of unrelated changes in this PR

File: plugins/deisa/deisa.cxx [hunk 1]
```diff
@@ -106,16 +104,15 @@ class deisa_plugin: public Plugin
...
-	~deisa_plugin() noexcept override
+	~deisa_plugin() noexcept
 	{
+		context().logger().info("Closing plugin");
 		try {
 			// call bridge release() so that we can clear things before destructor is called (if it is ever called !).
+			assert(m_bridge != py::none());
 			assert(hasattr(m_bridge, "release"));
-			m_bridge.release();
+			m_bridge.attr("release")();
```
Comment (jbigot) [inline plugins/deisa/deisa.cxx:114]: the looks like the one actual relevant change to me. Not sure about the rest.

**Review by JAuriac — APPROVED** [review]

**Review by jbigot — APPROVED** [review]
Looks great
